# Javascript Angular CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11-browsers

    working_directory: ~/angular

    steps:
      - checkout

      - restore_cache:
          keys:
          - angular-demo-dependencies-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - angular-demo-dependencies-

      - run:
          name: install-dependencies
          command: yarn install

      - save_cache:
          key: angular-demo-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ./node_modules

      - run:
          name: Build
          command: yarn build

      - persist_to_workspace:
          root: ~/angular
          paths:
            - dist

      # - run:
      #     name: Code Quality
      #     command: yarn lint

      #- run:
      #    name: Test
      #    command: yarn test

  deploy-AWS:
    docker:
      - image: circleci/python:2.7

    working_directory: ~/angular

    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/ng-ngrx-forms-demo

      - run:
          name: Install AWS CLI
          command: sudo pip install awscli

      - run:
          name: Deploy to AWS S3
          command: aws s3 sync ~/angular/dist s3://circleciwebapptest/ --delete --acl public-read

workflows:
  version: 2
  build-deploy-app:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
              branches:
                only: master
